"""Criação inicial de todas as tabelas

Revision ID: 4646ef880aa6
Revises: 
Create Date: 2025-08-29 19:57:03.449468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4646ef880aa6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('email_notificacoes', sa.Boolean(), nullable=True),
    sa.Column('app_notificacoes', sa.Boolean(), nullable=True),
    sa.Column('frequencia_notificacoes', sa.String(length=20), nullable=True),
    sa.Column('token_confirmacao', sa.String(length=255), nullable=True),
    sa.Column('token_expiracao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('disciplina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('professor', sa.String(length=150), nullable=True),
    sa.Column('periodo', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ATIVA', 'CONCLUIDA', 'ANDAMENTO', name='statusdisciplina'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('TAREFA', 'PROVA', 'DISCIPLINA', 'SISTEMA', name='tiponotificacao'), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarefa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_entrega', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('A_FAZER', 'ANDAMENTO', 'CONCLUIDA', 'ATRASADA', name='statustarefa'), nullable=False),
    sa.Column('tipo', sa.Enum('TAREFA', 'PROVA', name='tipotarefa'), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anotacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_modificacao', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=True),
    sa.Column('tarefa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anotacao')
    op.drop_table('tarefa')
    op.drop_table('notificacao')
    op.drop_table('disciplina')
    op.drop_table('usuario')
    # ### end Alembic commands ###
